apiVersion: v1
kind: Service
metadata:
  name: static-webpage-service
spec:
  selector:
    app: static-webpage
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30000   # Assuming you want to use port 30000 on the host machine
  type: NodePort
